# Generated by Django 3.2.23 on 2023-12-26 23:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20231226_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/dg7zlxltx/5576d848bf1559baa27e894c5cd0b089', max_length=255, verbose_name='image'),
        ),
    ]
